apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraminer-ml-service
  namespace: argocd
spec:
  project: terraminer
  source:
    repoURL: https://github.com/terraminer/infrastructure.git
    targetRevision: HEAD
    path: helm/ml-service
    helm:
      valueFiles:
      - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: terraminer-ml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m