"use client";

import { useState } from "react";
import {
  FileText,
  Download,
  FileSpreadsheet,
  Loader2,
  CheckCircle,
  Calendar,
  Building2,
  Scale,
} from "lucide-react";
import { cn } from "@/lib/utils";

interface ReportConfig {
  format: "pdf" | "csv" | "xlsx";
  includeComparables: boolean;
  includeHistory: boolean;
  includeNotes: boolean;
  taxYear: number;
}

interface AssessmentReportExportProps {
  propertyId: string;
  propertyAddress: string;
  className?: string;
}

export function AssessmentReportExport({
  propertyId,
  propertyAddress,
  className,
}: AssessmentReportExportProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [config, setConfig] = useState<ReportConfig>({
    format: "pdf",
    includeComparables: true,
    includeHistory: true,
    includeNotes: false,
    taxYear: new Date().getFullYear(),
  });

  const handleGenerate = async () => {
    setIsGenerating(true);
    
    // Simulate report generation
    await new Promise((resolve) => setTimeout(resolve, 2000));
    
    // In production, this would call an API endpoint
    // For demo, we'll create a simple text file download
    const reportContent = generateReportContent();
    
    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `assessment-report-${propertyId}-${config.taxYear}.${config.format === "pdf" ? "txt" : config.format}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    setIsGenerating(false);
    setGenerated(true);
    setTimeout(() => setGenerated(false), 3000);
  };

  const generateReportContent = () => {
    const lines = [
      "=" .repeat(60),
      "BENTON COUNTY ASSESSOR'S OFFICE",
      "Property Assessment Report",
      "=" .repeat(60),
      "",
      `Property ID: ${propertyId}`,
      `Address: ${propertyAddress}`,
      `Tax Year: ${config.taxYear}`,
      `Generated: ${new Date().toLocaleString()}`,
      "",
      "-".repeat(60),
      "ASSESSMENT SUMMARY",
      "-".repeat(60),
      "",
      "This is a demo report. In production, this would include:",
      "",
      config.includeComparables ? "✓ Comparable Sales Analysis" : "✗ Comparable Sales Analysis",
      config.includeHistory ? "✓ Assessment History (5 years)" : "✗ Assessment History",
      config.includeNotes ? "✓ Assessor Notes & Annotations" : "✗ Assessor Notes",
      "",
      "-".repeat(60),
      "IAAO COMPLIANCE",
      "-".repeat(60),
      "",
      "Median Ratio: 0.950",
      "COD: 8.5%",
      "PRD: 1.02",
      "PRB: -0.01",
      "Status: COMPLIANT",
      "",
      "=" .repeat(60),
      "Report generated by TerraFusion Assessment Platform",
      "Powered by TerraEngine v2.0",
      "=" .repeat(60),
    ];
    
    return lines.join("\n");
  };

  const FORMAT_OPTIONS = [
    { id: "pdf", label: "PDF Report", icon: FileText, description: "Full formatted report" },
    { id: "csv", label: "CSV Export", icon: FileSpreadsheet, description: "Raw data spreadsheet" },
    { id: "xlsx", label: "Excel Export", icon: FileSpreadsheet, description: "Formatted spreadsheet" },
  ] as const;

  const TAX_YEARS = [2025, 2024, 2023, 2022, 2021];

  return (
    <div className={cn("relative", className)}>
      {/* Trigger Button */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={cn(
          "flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-medium transition-colors",
          isOpen
            ? "border-primary bg-primary/10 text-primary"
            : "border-border bg-card text-muted-foreground hover:border-primary hover:text-primary"
        )}
      >
        <FileText className="h-4 w-4" />
        Export Report
      </button>

      {/* Dropdown Panel */}
      {isOpen && (
        <div className="absolute right-0 top-full z-50 mt-2 w-80 rounded-lg border border-border bg-card p-4 shadow-xl animate-slide-in">
          {/* Header */}
          <div className="mb-4 flex items-center gap-2">
            <Scale className="h-4 w-4 text-primary" />
            <h3 className="text-sm font-semibold text-foreground">Assessment Report</h3>
          </div>

          {/* Tax Year */}
          <div className="mb-4">
            <label className="mb-1.5 block text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
              Tax Year
            </label>
            <div className="flex gap-1.5">
              {TAX_YEARS.map((year) => (
                <button
                  key={year}
                  onClick={() => setConfig({ ...config, taxYear: year })}
                  className={cn(
                    "flex-1 rounded-md px-2 py-1.5 text-xs font-medium transition-colors",
                    config.taxYear === year
                      ? "bg-primary text-primary-foreground"
                      : "bg-accent text-muted-foreground hover:text-foreground"
                  )}
                >
                  {year}
                </button>
              ))}
            </div>
          </div>

          {/* Format */}
          <div className="mb-4">
            <label className="mb-1.5 block text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
              Format
            </label>
            <div className="flex flex-col gap-1.5">
              {FORMAT_OPTIONS.map((option) => {
                const Icon = option.icon;
                return (
                  <button
                    key={option.id}
                    onClick={() => setConfig({ ...config, format: option.id })}
                    className={cn(
                      "flex items-center gap-3 rounded-md px-3 py-2 text-left transition-colors",
                      config.format === option.id
                        ? "bg-primary/10 text-primary"
                        : "bg-accent/50 text-foreground hover:bg-accent"
                    )}
                  >
                    <Icon className="h-4 w-4 shrink-0" />
                    <div className="flex-1">
                      <p className="text-xs font-medium">{option.label}</p>
                      <p className="text-[10px] text-muted-foreground">{option.description}</p>
                    </div>
                    {config.format === option.id && (
                      <CheckCircle className="h-4 w-4 shrink-0 text-primary" />
                    )}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Include Options */}
          <div className="mb-4">
            <label className="mb-1.5 block text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
              Include in Report
            </label>
            <div className="flex flex-col gap-2">
              <label className="flex cursor-pointer items-center gap-2">
                <input
                  type="checkbox"
                  checked={config.includeComparables}
                  onChange={(e) => setConfig({ ...config, includeComparables: e.target.checked })}
                  className="h-3.5 w-3.5 rounded border-border text-primary focus:ring-primary"
                />
                <span className="text-xs text-foreground">Comparable Sales Analysis</span>
              </label>
              <label className="flex cursor-pointer items-center gap-2">
                <input
                  type="checkbox"
                  checked={config.includeHistory}
                  onChange={(e) => setConfig({ ...config, includeHistory: e.target.checked })}
                  className="h-3.5 w-3.5 rounded border-border text-primary focus:ring-primary"
                />
                <span className="text-xs text-foreground">5-Year Assessment History</span>
              </label>
              <label className="flex cursor-pointer items-center gap-2">
                <input
                  type="checkbox"
                  checked={config.includeNotes}
                  onChange={(e) => setConfig({ ...config, includeNotes: e.target.checked })}
                  className="h-3.5 w-3.5 rounded border-border text-primary focus:ring-primary"
                />
                <span className="text-xs text-foreground">Assessor Notes</span>
              </label>
            </div>
          </div>

          {/* Generate Button */}
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className={cn(
              "flex w-full items-center justify-center gap-2 rounded-lg py-2.5 text-sm font-medium transition-colors",
              generated
                ? "bg-[hsl(var(--success))] text-white"
                : "bg-primary text-primary-foreground hover:bg-primary/90",
              isGenerating && "cursor-not-allowed opacity-70"
            )}
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : generated ? (
              <>
                <CheckCircle className="h-4 w-4" />
                Downloaded!
              </>
            ) : (
              <>
                <Download className="h-4 w-4" />
                Generate & Download
              </>
            )}
          </button>

          {/* Footer */}
          <p className="mt-3 text-center text-[10px] text-muted-foreground">
            Report will include IAAO compliance metrics
          </p>
        </div>
      )}
    </div>
  );
}
