// ============================================================================
// Mock property listings -- these houses are real in my imagination
// Tri-Cities WA region: Richland, Kennewick, Pasco, West Richland
// ============================================================================

export interface Property {
  id: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  price: number;
  beds: number;
  baths: number;
  sqft: number;
  lotSize: number;
  yearBuilt: number;
  propertyType: "single-family" | "condo" | "townhouse" | "multi-family" | "land";
  status: "active" | "pending" | "sold" | "new";
  daysOnMarket: number;
  description: string;
  features: string[];
  mlsId: string;
  latitude: number;
  longitude: number;
}

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "prop-001",
    address: "1234 Jadwin Ave",
    city: "Richland",
    state: "WA",
    zip: "99352",
    price: 425000,
    beds: 4,
    baths: 2.5,
    sqft: 2200,
    lotSize: 8500,
    yearBuilt: 2018,
    propertyType: "single-family",
    status: "active",
    daysOnMarket: 12,
    description: "Beautiful modern home in South Richland with mountain views and updated kitchen.",
    features: ["Mountain View", "Updated Kitchen", "2-Car Garage", "Central AC"],
    mlsId: "MLS-TF-9001",
    latitude: 46.2856,
    longitude: -119.2845,
  },
  {
    id: "prop-002",
    address: "567 Columbia Park Trail",
    city: "Richland",
    state: "WA",
    zip: "99352",
    price: 389000,
    beds: 3,
    baths: 2,
    sqft: 1850,
    lotSize: 7200,
    yearBuilt: 2015,
    propertyType: "single-family",
    status: "new",
    daysOnMarket: 3,
    description: "Charming craftsman near Columbia Park with river trail access.",
    features: ["River Access", "Hardwood Floors", "Fireplace", "Fenced Yard"],
    mlsId: "MLS-TF-9002",
    latitude: 46.2765,
    longitude: -119.2734,
  },
  {
    id: "prop-003",
    address: "890 Clearwater Ave",
    city: "Kennewick",
    state: "WA",
    zip: "99336",
    price: 315000,
    beds: 3,
    baths: 2,
    sqft: 1600,
    lotSize: 6800,
    yearBuilt: 2010,
    propertyType: "single-family",
    status: "active",
    daysOnMarket: 21,
    description: "Well-maintained home near Southridge area with open floor plan.",
    features: ["Open Floor Plan", "Granite Counters", "Sprinkler System", "Patio"],
    mlsId: "MLS-TF-9003",
    latitude: 46.2112,
    longitude: -119.1756,
  },
  {
    id: "prop-004",
    address: "2100 Road 68",
    city: "Pasco",
    state: "WA",
    zip: "99301",
    price: 275000,
    beds: 3,
    baths: 1.5,
    sqft: 1400,
    lotSize: 5500,
    yearBuilt: 2005,
    propertyType: "single-family",
    status: "active",
    daysOnMarket: 35,
    description: "Affordable family home in growing Pasco neighborhood near schools.",
    features: ["Near Schools", "New Roof", "Vinyl Fencing", "RV Parking"],
    mlsId: "MLS-TF-9004",
    latitude: 46.2396,
    longitude: -119.2851,
  },
  {
    id: "prop-005",
    address: "4521 Meadow Hills Dr",
    city: "West Richland",
    state: "WA",
    zip: "99353",
    price: 545000,
    beds: 5,
    baths: 3,
    sqft: 3100,
    lotSize: 12000,
    yearBuilt: 2021,
    propertyType: "single-family",
    status: "active",
    daysOnMarket: 8,
    description: "Luxury new construction in Meadow Hills with smart home features.",
    features: ["Smart Home", "Wine Cellar", "3-Car Garage", "Solar Panels"],
    mlsId: "MLS-TF-9005",
    latitude: 46.3045,
    longitude: -119.3612,
  },
  {
    id: "prop-006",
    address: "321 George Washington Way",
    city: "Richland",
    state: "WA",
    zip: "99352",
    price: 225000,
    beds: 2,
    baths: 1,
    sqft: 1100,
    lotSize: 4200,
    yearBuilt: 1965,
    propertyType: "single-family",
    status: "pending",
    daysOnMarket: 7,
    description: "Classic mid-century home in the Richland Y area. Great starter home.",
    features: ["Original Hardwood", "Large Lot", "Mature Trees", "Detached Shop"],
    mlsId: "MLS-TF-9006",
    latitude: 46.2734,
    longitude: -119.2789,
  },
  {
    id: "prop-007",
    address: "1550 Columbia Center Blvd #204",
    city: "Kennewick",
    state: "WA",
    zip: "99336",
    price: 189000,
    beds: 2,
    baths: 2,
    sqft: 950,
    lotSize: 0,
    yearBuilt: 2008,
    propertyType: "condo",
    status: "active",
    daysOnMarket: 45,
    description: "Low-maintenance condo near Columbia Center Mall. HOA includes pool.",
    features: ["Pool Access", "Gym", "Covered Parking", "In-Unit Laundry"],
    mlsId: "MLS-TF-9007",
    latitude: 46.2178,
    longitude: -119.2234,
  },
  {
    id: "prop-008",
    address: "820 Bombing Range Rd",
    city: "West Richland",
    state: "WA",
    zip: "99353",
    price: 475000,
    beds: 4,
    baths: 2.5,
    sqft: 2600,
    lotSize: 10000,
    yearBuilt: 2019,
    propertyType: "single-family",
    status: "sold",
    daysOnMarket: 14,
    description: "Stunning craftsman in West Richland with Badger Mountain views.",
    features: ["Mountain View", "Chef Kitchen", "Bonus Room", "Covered Patio"],
    mlsId: "MLS-TF-9008",
    latitude: 46.3123,
    longitude: -119.3456,
  },
  {
    id: "prop-009",
    address: "3345 W Kennewick Ave",
    city: "Kennewick",
    state: "WA",
    zip: "99336",
    price: 340000,
    beds: 3,
    baths: 2,
    sqft: 1750,
    lotSize: 7500,
    yearBuilt: 2012,
    propertyType: "townhouse",
    status: "active",
    daysOnMarket: 18,
    description: "Modern townhouse with low-maintenance living in prime Kennewick location.",
    features: ["End Unit", "Attached Garage", "Upgraded Appliances", "Private Patio"],
    mlsId: "MLS-TF-9009",
    latitude: 46.2089,
    longitude: -119.2345,
  },
  {
    id: "prop-010",
    address: "7890 Gage Blvd",
    city: "Kennewick",
    state: "WA",
    zip: "99336",
    price: 510000,
    beds: 4,
    baths: 3,
    sqft: 2800,
    lotSize: 9500,
    yearBuilt: 2020,
    propertyType: "single-family",
    status: "new",
    daysOnMarket: 1,
    description: "Brand new listing! Premium Southridge home with pool and outdoor kitchen.",
    features: ["Pool", "Outdoor Kitchen", "Theater Room", "3-Car Garage"],
    mlsId: "MLS-TF-9010",
    latitude: 46.1945,
    longitude: -119.1867,
  },
  {
    id: "prop-011",
    address: "445 Thayer Dr",
    city: "Richland",
    state: "WA",
    zip: "99352",
    price: 365000,
    beds: 3,
    baths: 2,
    sqft: 1900,
    lotSize: 8000,
    yearBuilt: 2014,
    propertyType: "single-family",
    status: "active",
    daysOnMarket: 28,
    description: "Quiet cul-de-sac location in Richland with spacious backyard.",
    features: ["Cul-de-Sac", "Vaulted Ceilings", "Walk-in Closet", "Sprinklers"],
    mlsId: "MLS-TF-9011",
    latitude: 46.2812,
    longitude: -119.2901,
  },
  {
    id: "prop-012",
    address: "6100 W Court St",
    city: "Pasco",
    state: "WA",
    zip: "99301",
    price: 299000,
    beds: 4,
    baths: 2,
    sqft: 1650,
    lotSize: 6200,
    yearBuilt: 2009,
    propertyType: "single-family",
    status: "active",
    daysOnMarket: 42,
    description: "Spacious 4-bed home in Pasco with large lot and storage.",
    features: ["Large Lot", "Extra Storage", "New Paint", "Updated Bathroom"],
    mlsId: "MLS-TF-9012",
    latitude: 46.2456,
    longitude: -119.1234,
  },
];
